// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateUserResponse struct {
	Data *User `json:"data,omitempty"`
}

func (c *CreateUserResponse) GetData() *User {
	if c == nil {
		return nil
	}
	return c.Data
}
