// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateStackRequest struct {
	// Stack name
	Name     string            `json:"name"`
	Metadata map[string]string `json:"metadata,omitempty"`
	// Supported only with agent version >= v0.7.0
	Version  *string `json:"version,omitempty"`
	RegionID string  `json:"regionID"`
}

func (c *CreateStackRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateStackRequest) GetMetadata() map[string]string {
	if c == nil {
		return nil
	}
	return c.Metadata
}

func (c *CreateStackRequest) GetVersion() *string {
	if c == nil {
		return nil
	}
	return c.Version
}

func (c *CreateStackRequest) GetRegionID() string {
	if c == nil {
		return ""
	}
	return c.RegionID
}
