// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateOrganizationResponse struct {
	Data *OrganizationExpanded `json:"data,omitempty"`
}

func (c *CreateOrganizationResponse) GetData() *OrganizationExpanded {
	if c == nil {
		return nil
	}
	return c.Data
}
