// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateApplicationScopeResponse struct {
	Data *Scope `json:"data,omitempty"`
}

func (c *CreateApplicationScopeResponse) GetData() *Scope {
	if c == nil {
		return nil
	}
	return c.Data
}
