// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateInvitationResponse struct {
	Data *Invitation `json:"data,omitempty"`
}

func (c *CreateInvitationResponse) GetData() *Invitation {
	if c == nil {
		return nil
	}
	return c.Data
}
