// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreatedPrivateRegionResponse struct {
	Data PrivateRegion `json:"data"`
}

func (c *CreatedPrivateRegionResponse) GetData() PrivateRegion {
	if c == nil {
		return PrivateRegion{}
	}
	return c.Data
}
