// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateOrganizationClientRequest struct {
	// Name of the client
	Name *string `json:"name,omitempty"`
	// Description of the client
	Description *string `json:"description,omitempty"`
}

func (c *CreateOrganizationClientRequest) GetName() *string {
	if c == nil {
		return nil
	}
	return c.Name
}

func (c *CreateOrganizationClientRequest) GetDescription() *string {
	if c == nil {
		return nil
	}
	return c.Description
}
