// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreatePolicyResponse struct {
	Data *Policy `json:"data,omitempty"`
}

func (c *CreatePolicyResponse) GetData() *Policy {
	if c == nil {
		return nil
	}
	return c.Data
}
