// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateApplicationResponse struct {
	Data *Application `json:"data,omitempty"`
}

func (c *CreateApplicationResponse) GetData() *Application {
	if c == nil {
		return nil
	}
	return c.Data
}
