// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateStackResponse struct {
	Data *Stack `json:"data,omitempty"`
}

func (c *CreateStackResponse) GetData() *Stack {
	if c == nil {
		return nil
	}
	return c.Data
}
