// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type CreateOrganizationRequest struct {
	// Organization name
	Name string `json:"name"`
	// Organization domain
	Domain *string `json:"domain,omitempty"`
	// Default policy ID applied to new users
	DefaultPolicyID *int64 `json:"defaultPolicyID,omitempty"`
	// User ID of the owner of the organization (only when used with a non user agent)
	OwnerID *string `json:"ownerID,omitempty"`
}

func (c *CreateOrganizationRequest) GetName() string {
	if c == nil {
		return ""
	}
	return c.Name
}

func (c *CreateOrganizationRequest) GetDomain() *string {
	if c == nil {
		return nil
	}
	return c.Domain
}

func (c *CreateOrganizationRequest) GetDefaultPolicyID() *int64 {
	if c == nil {
		return nil
	}
	return c.DefaultPolicyID
}

func (c *CreateOrganizationRequest) GetOwnerID() *string {
	if c == nil {
		return nil
	}
	return c.OwnerID
}
