// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type EnableApplicationForOrganizationResponse struct {
	Data *OrganizationApplication `json:"data,omitempty"`
}

func (e *EnableApplicationForOrganizationResponse) GetData() *OrganizationApplication {
	if e == nil {
		return nil
	}
	return e.Data
}
