// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetApplicationResponse struct {
	Data *ApplicationWithScope `json:"data,omitempty"`
}

func (g *GetApplicationResponse) GetData() *ApplicationWithScope {
	if g == nil {
		return nil
	}
	return g.Data
}
