// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type GetRegionResponse struct {
	Data AnyRegion `json:"data"`
}

func (g *GetRegionResponse) GetData() AnyRegion {
	if g == nil {
		return AnyRegion{}
	}
	return g.Data
}
