// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListRegionsResponse struct {
	Data []AnyRegion `json:"data"`
}

func (l *ListRegionsResponse) GetData() []AnyRegion {
	if l == nil {
		return []AnyRegion{}
	}
	return l.Data
}
