// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListOrganizationExpandedResponse struct {
	Data []OrganizationExpanded `json:"data,omitempty"`
}

func (l *ListOrganizationExpandedResponse) GetData() []OrganizationExpanded {
	if l == nil {
		return nil
	}
	return l.Data
}
