// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListInvitationsResponse struct {
	Data []Invitation `json:"data,omitempty"`
}

func (l *ListInvitationsResponse) GetData() []Invitation {
	if l == nil {
		return nil
	}
	return l.Data
}
