// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OrganizationUser struct {
	Email string `json:"email"`
	ID    string `json:"id"`
	// Policy ID applied to the user
	PolicyID int64 `json:"policyId"`
}

func (o *OrganizationUser) GetEmail() string {
	if o == nil {
		return ""
	}
	return o.Email
}

func (o *OrganizationUser) GetID() string {
	if o == nil {
		return ""
	}
	return o.ID
}

func (o *OrganizationUser) GetPolicyID() int64 {
	if o == nil {
		return 0
	}
	return o.PolicyID
}

type ListUsersResponse struct {
	Data []OrganizationUser `json:"data,omitempty"`
}

func (l *ListUsersResponse) GetData() []OrganizationUser {
	if l == nil {
		return nil
	}
	return l.Data
}
