// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListStacksResponse struct {
	Data []Stack `json:"data,omitempty"`
}

func (l *ListStacksResponse) GetData() []Stack {
	if l == nil {
		return nil
	}
	return l.Data
}
