// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type Cursor struct {
	PageSize int64         `json:"pageSize"`
	HasMore  bool          `json:"hasMore"`
	Previous *string       `json:"previous,omitempty"`
	Next     *string       `json:"next,omitempty"`
	Data     []Application `json:"data"`
}

func (c *Cursor) GetPageSize() int64 {
	if c == nil {
		return 0
	}
	return c.PageSize
}

func (c *Cursor) GetHasMore() bool {
	if c == nil {
		return false
	}
	return c.HasMore
}

func (c *Cursor) GetPrevious() *string {
	if c == nil {
		return nil
	}
	return c.Previous
}

func (c *Cursor) GetNext() *string {
	if c == nil {
		return nil
	}
	return c.Next
}

func (c *Cursor) GetData() []Application {
	if c == nil {
		return []Application{}
	}
	return c.Data
}

type ListApplicationsResponse struct {
	Cursor *Cursor `json:"cursor,omitempty"`
}

func (l *ListApplicationsResponse) GetCursor() *Cursor {
	if l == nil {
		return nil
	}
	return l.Cursor
}
