// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ListPoliciesResponse struct {
	Data []Policy `json:"data,omitempty"`
}

func (l *ListPoliciesResponse) GetData() []Policy {
	if l == nil {
		return nil
	}
	return l.Data
}
