// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type OrganizationData struct {
	// Organization name
	Name string `json:"name"`
	// Organization domain
	Domain *string `json:"domain,omitempty"`
	// Default policy ID applied to new users
	DefaultPolicyID *int64 `json:"defaultPolicyID"`
}

func (o *OrganizationData) GetName() string {
	if o == nil {
		return ""
	}
	return o.Name
}

func (o *OrganizationData) GetDomain() *string {
	if o == nil {
		return nil
	}
	return o.Domain
}

func (o *OrganizationData) GetDefaultPolicyID() *int64 {
	if o == nil {
		return nil
	}
	return o.DefaultPolicyID
}
