// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/utils"
	"time"
)

type Policy struct {
	// Policy name
	Name string `json:"name"`
	// Policy description
	Description *string `json:"description,omitempty"`
	// Policy ID
	ID int64 `json:"id"`
	// Organization ID
	OrganizationID *string `json:"organizationId,omitempty"`
	// Whether the policy is protected from modification
	Protected bool `json:"protected"`
	// List of scopes assigned to the policy (only present when fetched via GET endpoint)
	Scopes []Scope `json:"scopes,omitempty"`
	// Creation date
	CreatedAt time.Time `json:"createdAt"`
	// Last update date
	UpdatedAt time.Time `json:"updatedAt"`
}

func (p Policy) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(p, "", false)
}

func (p *Policy) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &p, "", false, []string{"name", "id", "protected", "createdAt", "updatedAt"}); err != nil {
		return err
	}
	return nil
}

func (p *Policy) GetName() string {
	if p == nil {
		return ""
	}
	return p.Name
}

func (p *Policy) GetDescription() *string {
	if p == nil {
		return nil
	}
	return p.Description
}

func (p *Policy) GetID() int64 {
	if p == nil {
		return 0
	}
	return p.ID
}

func (p *Policy) GetOrganizationID() *string {
	if p == nil {
		return nil
	}
	return p.OrganizationID
}

func (p *Policy) GetProtected() bool {
	if p == nil {
		return false
	}
	return p.Protected
}

func (p *Policy) GetScopes() []Scope {
	if p == nil {
		return nil
	}
	return p.Scopes
}

func (p *Policy) GetCreatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.CreatedAt
}

func (p *Policy) GetUpdatedAt() time.Time {
	if p == nil {
		return time.Time{}
	}
	return p.UpdatedAt
}
