// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type PrivateRegionSecret struct {
	LastDigits string  `json:"lastDigits"`
	Clear      *string `json:"clear,omitempty"`
}

func (p *PrivateRegionSecret) GetLastDigits() string {
	if p == nil {
		return ""
	}
	return p.LastDigits
}

func (p *PrivateRegionSecret) GetClear() *string {
	if p == nil {
		return nil
	}
	return p.Clear
}
