// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ReadPolicyResponse struct {
	Data *Policy `json:"data,omitempty"`
}

func (r *ReadPolicyResponse) GetData() *Policy {
	if r == nil {
		return nil
	}
	return r.Data
}
