// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type RegionCapability struct {
	ModuleList []string `json:"MODULE_LIST,omitempty"`
	Ee         []string `json:"EE,omitempty"`
}

func (r *RegionCapability) GetModuleList() []string {
	if r == nil {
		return nil
	}
	return r.ModuleList
}

func (r *RegionCapability) GetEe() []string {
	if r == nil {
		return nil
	}
	return r.Ee
}
