// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type ServerInfo struct {
	Version      string       `json:"version"`
	Capabilities []Capability `json:"capabilities,omitempty"`
	ConsoleURL   *string      `json:"consoleURL,omitempty"`
}

func (s *ServerInfo) GetVersion() string {
	if s == nil {
		return ""
	}
	return s.Version
}

func (s *ServerInfo) GetCapabilities() []Capability {
	if s == nil {
		return nil
	}
	return s.Capabilities
}

func (s *ServerInfo) GetConsoleURL() *string {
	if s == nil {
		return nil
	}
	return s.ConsoleURL
}
