// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type StackData struct {
	// Stack name
	Name     string            `json:"name"`
	Metadata map[string]string `json:"metadata,omitempty"`
}

func (s *StackData) GetName() string {
	if s == nil {
		return ""
	}
	return s.Name
}

func (s *StackData) GetMetadata() map[string]string {
	if s == nil {
		return nil
	}
	return s.Metadata
}
