// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/optionalnullable"
)

type StackUserAccessResponseData struct {
	// Stack ID
	StackID string `json:"stackId"`
	// User ID
	UserID string `json:"userId"`
	// User email
	Email string `json:"email"`
	// Policy ID applied to the user for the stack
	PolicyID int64 `json:"policyId"`
	// Policy ID applied to the user at the organization level
	OrganizationPolicyID optionalnullable.OptionalNullable[int64] `json:"organizationPolicyId,omitempty"`
}

func (s *StackUserAccessResponseData) GetStackID() string {
	if s == nil {
		return ""
	}
	return s.StackID
}

func (s *StackUserAccessResponseData) GetUserID() string {
	if s == nil {
		return ""
	}
	return s.UserID
}

func (s *StackUserAccessResponseData) GetEmail() string {
	if s == nil {
		return ""
	}
	return s.Email
}

func (s *StackUserAccessResponseData) GetPolicyID() int64 {
	if s == nil {
		return 0
	}
	return s.PolicyID
}

func (s *StackUserAccessResponseData) GetOrganizationPolicyID() optionalnullable.OptionalNullable[int64] {
	if s == nil {
		return nil
	}
	return s.OrganizationPolicyID
}

type StackUserAccessResponse struct {
	Data []StackUserAccessResponseData `json:"data,omitempty"`
}

func (s *StackUserAccessResponse) GetData() []StackUserAccessResponseData {
	if s == nil {
		return nil
	}
	return s.Data
}
