// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdatePolicyResponse struct {
	Data *Policy `json:"data,omitempty"`
}

func (u *UpdatePolicyResponse) GetData() *Policy {
	if u == nil {
		return nil
	}
	return u.Data
}
