// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateOrganizationUserRequest struct {
	// Policy ID applied to the user
	PolicyID *int64 `json:"policyId,omitempty"`
}

func (u *UpdateOrganizationUserRequest) GetPolicyID() *int64 {
	if u == nil {
		return nil
	}
	return u.PolicyID
}
