// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateStackUserRequest struct {
	PolicyID int64 `json:"policyId"`
}

func (u *UpdateStackUserRequest) GetPolicyID() int64 {
	if u == nil {
		return 0
	}
	return u.PolicyID
}
