// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package shared

type UpdateApplicationResponse struct {
	Data *Application `json:"data,omitempty"`
}

func (u *UpdateApplicationResponse) GetData() *Application {
	if u == nil {
		return nil
	}
	return u.Data
}
