// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider/internal/membership (interfaces: TokenProviderImpl)
//
// Generated by this command:
//
//	mockgen -destination=tokenprovider_generated.go -package=membership . TokenProviderImpl
//

// Package membership is a generated GoMock package.
package membership

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenProviderImpl is a mock of TokenProviderImpl interface.
type MockTokenProviderImpl struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderImplMockRecorder
	isgomock struct{}
}

// MockTokenProviderImplMockRecorder is the mock recorder for MockTokenProviderImpl.
type MockTokenProviderImplMockRecorder struct {
	mock *MockTokenProviderImpl
}

// NewMockTokenProviderImpl creates a new mock instance.
func NewMockTokenProviderImpl(ctrl *gomock.Controller) *MockTokenProviderImpl {
	mock := &MockTokenProviderImpl{ctrl: ctrl}
	mock.recorder = &MockTokenProviderImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProviderImpl) EXPECT() *MockTokenProviderImplMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockTokenProviderImpl) AccessToken(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockTokenProviderImplMockRecorder) AccessToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).AccessToken), ctx)
}

// RefreshToken mocks base method.
func (m *MockTokenProviderImpl) RefreshToken(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockTokenProviderImplMockRecorder) RefreshToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).RefreshToken), ctx)
}

// RunE mocks base method.
func (m *MockTokenProviderImpl) RunE(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunE", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RunE indicates an expected call of RunE.
func (mr *MockTokenProviderImplMockRecorder) RunE(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunE", reflect.TypeOf((*MockTokenProviderImpl)(nil).RunE), ctx)
}
