// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type AcceptInvitationRequest struct {
	InvitationID string `pathParam:"style=simple,explode=false,name=invitationId"`
}

func (a *AcceptInvitationRequest) GetInvitationID() string {
	if a == nil {
		return ""
	}
	return a.InvitationID
}

type AcceptInvitationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (a *AcceptInvitationResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AcceptInvitationResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AcceptInvitationResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AcceptInvitationResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
