// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type AddFeaturesRequestBody struct {
	Features []string `json:"features"`
}

func (a *AddFeaturesRequestBody) GetFeatures() []string {
	if a == nil {
		return []string{}
	}
	return a.Features
}

type AddFeaturesRequest struct {
	OrganizationID string                  `pathParam:"style=simple,explode=false,name=organizationId"`
	RequestBody    *AddFeaturesRequestBody `request:"mediaType=application/json"`
}

func (a *AddFeaturesRequest) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *AddFeaturesRequest) GetRequestBody() *AddFeaturesRequestBody {
	if a == nil {
		return nil
	}
	return a.RequestBody
}

type AddFeaturesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (a *AddFeaturesResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AddFeaturesResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AddFeaturesResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AddFeaturesResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
