// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type AddScopeToPolicyRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64  `pathParam:"style=simple,explode=false,name=policyId"`
	ScopeID        int64  `pathParam:"style=simple,explode=false,name=scopeId"`
}

func (a *AddScopeToPolicyRequest) GetOrganizationID() string {
	if a == nil {
		return ""
	}
	return a.OrganizationID
}

func (a *AddScopeToPolicyRequest) GetPolicyID() int64 {
	if a == nil {
		return 0
	}
	return a.PolicyID
}

func (a *AddScopeToPolicyRequest) GetScopeID() int64 {
	if a == nil {
		return 0
	}
	return a.ScopeID
}

type AddScopeToPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (a *AddScopeToPolicyResponse) GetContentType() string {
	if a == nil {
		return ""
	}
	return a.ContentType
}

func (a *AddScopeToPolicyResponse) GetStatusCode() int {
	if a == nil {
		return 0
	}
	return a.StatusCode
}

func (a *AddScopeToPolicyResponse) GetRawResponse() *http.Response {
	if a == nil {
		return nil
	}
	return a.RawResponse
}

func (a *AddScopeToPolicyResponse) GetError() *shared.Error {
	if a == nil {
		return nil
	}
	return a.Error
}
