// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type CreatePolicyRequest struct {
	OrganizationID string             `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyData     *shared.PolicyData `request:"mediaType=application/json"`
}

func (c *CreatePolicyRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CreatePolicyRequest) GetPolicyData() *shared.PolicyData {
	if c == nil {
		return nil
	}
	return c.PolicyData
}

type CreatePolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Policy created
	CreatePolicyResponse *shared.CreatePolicyResponse
	// Error
	Error *shared.Error
}

func (c *CreatePolicyResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreatePolicyResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreatePolicyResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreatePolicyResponse) GetCreatePolicyResponse() *shared.CreatePolicyResponse {
	if c == nil {
		return nil
	}
	return c.CreatePolicyResponse
}

func (c *CreatePolicyResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
