// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type CreateApplicationScopeRequest struct {
	// The unique identifier of the application (UUID format)
	ApplicationID                 string                                `pathParam:"style=simple,explode=false,name=applicationId"`
	CreateApplicationScopeRequest *shared.CreateApplicationScopeRequest `request:"mediaType=application/json"`
}

func (c *CreateApplicationScopeRequest) GetApplicationID() string {
	if c == nil {
		return ""
	}
	return c.ApplicationID
}

func (c *CreateApplicationScopeRequest) GetCreateApplicationScopeRequest() *shared.CreateApplicationScopeRequest {
	if c == nil {
		return nil
	}
	return c.CreateApplicationScopeRequest
}

type CreateApplicationScopeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Application scope created
	CreateApplicationScopeResponse *shared.CreateApplicationScopeResponse
	// Error
	Error *shared.Error
}

func (c *CreateApplicationScopeResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateApplicationScopeResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateApplicationScopeResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateApplicationScopeResponse) GetCreateApplicationScopeResponse() *shared.CreateApplicationScopeResponse {
	if c == nil {
		return nil
	}
	return c.CreateApplicationScopeResponse
}

func (c *CreateApplicationScopeResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
