// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type CreateInvitationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	Email          string `queryParam:"style=form,explode=true,name=email"`
}

func (c *CreateInvitationRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CreateInvitationRequest) GetEmail() string {
	if c == nil {
		return ""
	}
	return c.Email
}

type CreateInvitationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invitation already sent
	CreateInvitationResponse *shared.CreateInvitationResponse
	// Error
	Error *shared.Error
}

func (c *CreateInvitationResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateInvitationResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateInvitationResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateInvitationResponse) GetCreateInvitationResponse() *shared.CreateInvitationResponse {
	if c == nil {
		return nil
	}
	return c.CreateInvitationResponse
}

func (c *CreateInvitationResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
