// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type CreatePrivateRegionRequest struct {
	OrganizationID             string                             `pathParam:"style=simple,explode=false,name=organizationId"`
	CreatePrivateRegionRequest *shared.CreatePrivateRegionRequest `request:"mediaType=application/json"`
}

func (c *CreatePrivateRegionRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CreatePrivateRegionRequest) GetCreatePrivateRegionRequest() *shared.CreatePrivateRegionRequest {
	if c == nil {
		return nil
	}
	return c.CreatePrivateRegionRequest
}

type CreatePrivateRegionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Created region
	CreatedPrivateRegionResponse *shared.CreatedPrivateRegionResponse
	// Error
	Error *shared.Error
}

func (c *CreatePrivateRegionResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreatePrivateRegionResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreatePrivateRegionResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreatePrivateRegionResponse) GetCreatedPrivateRegionResponse() *shared.CreatedPrivateRegionResponse {
	if c == nil {
		return nil
	}
	return c.CreatedPrivateRegionResponse
}

func (c *CreatePrivateRegionResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
