// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type CreateUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// User created successfully
	CreateUserResponse *shared.CreateUserResponse
	// Invalid request (missing or invalid email)
	Error *shared.Error
}

func (c *CreateUserResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateUserResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateUserResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateUserResponse) GetCreateUserResponse() *shared.CreateUserResponse {
	if c == nil {
		return nil
	}
	return c.CreateUserResponse
}

func (c *CreateUserResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
