// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type CreateOrganizationClientRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (c *CreateOrganizationClientRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

type CreateOrganizationClientResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Client organization created
	CreateClientResponseResponse *shared.CreateClientResponseResponse
	// Error
	Error *shared.Error
}

func (c *CreateOrganizationClientResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrganizationClientResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrganizationClientResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrganizationClientResponse) GetCreateClientResponseResponse() *shared.CreateClientResponseResponse {
	if c == nil {
		return nil
	}
	return c.CreateClientResponseResponse
}

func (c *CreateOrganizationClientResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
