// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type CreateStackRequest struct {
	OrganizationID     string                     `pathParam:"style=simple,explode=false,name=organizationId"`
	CreateStackRequest *shared.CreateStackRequest `request:"mediaType=application/json"`
}

func (c *CreateStackRequest) GetOrganizationID() string {
	if c == nil {
		return ""
	}
	return c.OrganizationID
}

func (c *CreateStackRequest) GetCreateStackRequest() *shared.CreateStackRequest {
	if c == nil {
		return nil
	}
	return c.CreateStackRequest
}

type CreateStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Stack created
	CreateStackResponse *shared.CreateStackResponse
	// Error
	Error *shared.Error
}

func (c *CreateStackResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateStackResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateStackResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateStackResponse) GetCreateStackResponse() *shared.CreateStackResponse {
	if c == nil {
		return nil
	}
	return c.CreateStackResponse
}

func (c *CreateStackResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
