// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type CreateApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Application created
	CreateApplicationResponse *shared.CreateApplicationResponse
	// Error
	Error *shared.Error
}

func (c *CreateApplicationResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateApplicationResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateApplicationResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateApplicationResponse) GetCreateApplicationResponse() *shared.CreateApplicationResponse {
	if c == nil {
		return nil
	}
	return c.CreateApplicationResponse
}

func (c *CreateApplicationResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
