// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type CreateOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Organization created
	CreateOrganizationResponse *shared.CreateOrganizationResponse
	// Error
	Error *shared.Error
}

func (c *CreateOrganizationResponse) GetContentType() string {
	if c == nil {
		return ""
	}
	return c.ContentType
}

func (c *CreateOrganizationResponse) GetStatusCode() int {
	if c == nil {
		return 0
	}
	return c.StatusCode
}

func (c *CreateOrganizationResponse) GetRawResponse() *http.Response {
	if c == nil {
		return nil
	}
	return c.RawResponse
}

func (c *CreateOrganizationResponse) GetCreateOrganizationResponse() *shared.CreateOrganizationResponse {
	if c == nil {
		return nil
	}
	return c.CreateOrganizationResponse
}

func (c *CreateOrganizationResponse) GetError() *shared.Error {
	if c == nil {
		return nil
	}
	return c.Error
}
