// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type DeclineInvitationRequest struct {
	InvitationID string `pathParam:"style=simple,explode=false,name=invitationId"`
}

func (d *DeclineInvitationRequest) GetInvitationID() string {
	if d == nil {
		return ""
	}
	return d.InvitationID
}

type DeclineInvitationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (d *DeclineInvitationResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeclineInvitationResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeclineInvitationResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeclineInvitationResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
