// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type DeletePolicyRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64  `pathParam:"style=simple,explode=false,name=policyId"`
}

func (d *DeletePolicyRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DeletePolicyRequest) GetPolicyID() int64 {
	if d == nil {
		return 0
	}
	return d.PolicyID
}

type DeletePolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (d *DeletePolicyResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeletePolicyResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeletePolicyResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeletePolicyResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
