// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type DeleteApplicationScopeRequest struct {
	// The unique identifier of the application (UUID format)
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
	// The unique identifier of the scope to operate on
	ScopeID int64 `pathParam:"style=simple,explode=false,name=scopeID"`
}

func (d *DeleteApplicationScopeRequest) GetApplicationID() string {
	if d == nil {
		return ""
	}
	return d.ApplicationID
}

func (d *DeleteApplicationScopeRequest) GetScopeID() int64 {
	if d == nil {
		return 0
	}
	return d.ScopeID
}

type DeleteApplicationScopeResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Invalid request (invalid UUID or empty scope ID)
	Error *shared.Error
}

func (d *DeleteApplicationScopeResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteApplicationScopeResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteApplicationScopeResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteApplicationScopeResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
