// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type DeleteOrganizationClientRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (d *DeleteOrganizationClientRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

type DeleteOrganizationClientResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (d *DeleteOrganizationClientResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteOrganizationClientResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteOrganizationClientResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteOrganizationClientResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
