// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type DeleteApplicationRequest struct {
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (d *DeleteApplicationRequest) GetApplicationID() string {
	if d == nil {
		return ""
	}
	return d.ApplicationID
}

type DeleteApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (d *DeleteApplicationResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DeleteApplicationResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DeleteApplicationResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DeleteApplicationResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
