// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type DisableModuleRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
	Name           string `queryParam:"style=form,explode=true,name=name"`
}

func (d *DisableModuleRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DisableModuleRequest) GetStackID() string {
	if d == nil {
		return ""
	}
	return d.StackID
}

func (d *DisableModuleRequest) GetName() string {
	if d == nil {
		return ""
	}
	return d.Name
}

type DisableModuleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (d *DisableModuleResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DisableModuleResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DisableModuleResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DisableModuleResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
