// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type DisableApplicationForOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ApplicationID  string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (d *DisableApplicationForOrganizationRequest) GetOrganizationID() string {
	if d == nil {
		return ""
	}
	return d.OrganizationID
}

func (d *DisableApplicationForOrganizationRequest) GetApplicationID() string {
	if d == nil {
		return ""
	}
	return d.ApplicationID
}

type DisableApplicationForOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (d *DisableApplicationForOrganizationResponse) GetContentType() string {
	if d == nil {
		return ""
	}
	return d.ContentType
}

func (d *DisableApplicationForOrganizationResponse) GetStatusCode() int {
	if d == nil {
		return 0
	}
	return d.StatusCode
}

func (d *DisableApplicationForOrganizationResponse) GetRawResponse() *http.Response {
	if d == nil {
		return nil
	}
	return d.RawResponse
}

func (d *DisableApplicationForOrganizationResponse) GetError() *shared.Error {
	if d == nil {
		return nil
	}
	return d.Error
}
