// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type EnableApplicationForOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ApplicationID  string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (e *EnableApplicationForOrganizationRequest) GetOrganizationID() string {
	if e == nil {
		return ""
	}
	return e.OrganizationID
}

func (e *EnableApplicationForOrganizationRequest) GetApplicationID() string {
	if e == nil {
		return ""
	}
	return e.ApplicationID
}

type EnableApplicationForOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Application enabled for organization
	EnableApplicationForOrganizationResponse *shared.EnableApplicationForOrganizationResponse
	// Error
	Error *shared.Error
}

func (e *EnableApplicationForOrganizationResponse) GetContentType() string {
	if e == nil {
		return ""
	}
	return e.ContentType
}

func (e *EnableApplicationForOrganizationResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *EnableApplicationForOrganizationResponse) GetRawResponse() *http.Response {
	if e == nil {
		return nil
	}
	return e.RawResponse
}

func (e *EnableApplicationForOrganizationResponse) GetEnableApplicationForOrganizationResponse() *shared.EnableApplicationForOrganizationResponse {
	if e == nil {
		return nil
	}
	return e.EnableApplicationForOrganizationResponse
}

func (e *EnableApplicationForOrganizationResponse) GetError() *shared.Error {
	if e == nil {
		return nil
	}
	return e.Error
}
