// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type EnableModuleRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
	Name           string `queryParam:"style=form,explode=true,name=name"`
}

func (e *EnableModuleRequest) GetOrganizationID() string {
	if e == nil {
		return ""
	}
	return e.OrganizationID
}

func (e *EnableModuleRequest) GetStackID() string {
	if e == nil {
		return ""
	}
	return e.StackID
}

func (e *EnableModuleRequest) GetName() string {
	if e == nil {
		return ""
	}
	return e.Name
}

type EnableModuleResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (e *EnableModuleResponse) GetContentType() string {
	if e == nil {
		return ""
	}
	return e.ContentType
}

func (e *EnableModuleResponse) GetStatusCode() int {
	if e == nil {
		return 0
	}
	return e.StatusCode
}

func (e *EnableModuleResponse) GetRawResponse() *http.Response {
	if e == nil {
		return nil
	}
	return e.RawResponse
}

func (e *EnableModuleResponse) GetError() *shared.Error {
	if e == nil {
		return nil
	}
	return e.Error
}
