// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type GetApplicationRequest struct {
	ApplicationID string `pathParam:"style=simple,explode=false,name=applicationId"`
}

func (g *GetApplicationRequest) GetApplicationID() string {
	if g == nil {
		return ""
	}
	return g.ApplicationID
}

type GetApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Application details
	GetApplicationResponse *shared.GetApplicationResponse
	// Error
	Error *shared.Error
}

func (g *GetApplicationResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetApplicationResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetApplicationResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetApplicationResponse) GetGetApplicationResponse() *shared.GetApplicationResponse {
	if g == nil {
		return nil
	}
	return g.GetApplicationResponse
}

func (g *GetApplicationResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
