// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type GetRegionRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	RegionID       string `pathParam:"style=simple,explode=false,name=regionID"`
}

func (g *GetRegionRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetRegionRequest) GetRegionID() string {
	if g == nil {
		return ""
	}
	return g.RegionID
}

type GetRegionResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Get a specific region
	GetRegionResponse *shared.GetRegionResponse
	// Error
	Error *shared.Error
}

func (g *GetRegionResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRegionResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRegionResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRegionResponse) GetGetRegionResponse() *shared.GetRegionResponse {
	if g == nil {
		return nil
	}
	return g.GetRegionResponse
}

func (g *GetRegionResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
