// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type GetRegionVersionsRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	RegionID       string `pathParam:"style=simple,explode=false,name=regionID"`
}

func (g *GetRegionVersionsRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetRegionVersionsRequest) GetRegionID() string {
	if g == nil {
		return ""
	}
	return g.RegionID
}

type GetRegionVersionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Get a specific region
	GetRegionVersionsResponse *shared.GetRegionVersionsResponse
	// Error
	Error *shared.Error
}

func (g *GetRegionVersionsResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetRegionVersionsResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetRegionVersionsResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetRegionVersionsResponse) GetGetRegionVersionsResponse() *shared.GetRegionVersionsResponse {
	if g == nil {
		return nil
	}
	return g.GetRegionVersionsResponse
}

func (g *GetRegionVersionsResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
