// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type GetStackRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
}

func (g *GetStackRequest) GetOrganizationID() string {
	if g == nil {
		return ""
	}
	return g.OrganizationID
}

func (g *GetStackRequest) GetStackID() string {
	if g == nil {
		return ""
	}
	return g.StackID
}

type GetStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateStackResponse *shared.CreateStackResponse
	// Error
	Error *shared.Error
}

func (g *GetStackResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetStackResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetStackResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetStackResponse) GetCreateStackResponse() *shared.CreateStackResponse {
	if g == nil {
		return nil
	}
	return g.CreateStackResponse
}

func (g *GetStackResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
