// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type GetServerInfoResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Server information
	ServerInfo *shared.ServerInfo
	// Error
	Error *shared.Error
}

func (g *GetServerInfoResponse) GetContentType() string {
	if g == nil {
		return ""
	}
	return g.ContentType
}

func (g *GetServerInfoResponse) GetStatusCode() int {
	if g == nil {
		return 0
	}
	return g.StatusCode
}

func (g *GetServerInfoResponse) GetRawResponse() *http.Response {
	if g == nil {
		return nil
	}
	return g.RawResponse
}

func (g *GetServerInfoResponse) GetServerInfo() *shared.ServerInfo {
	if g == nil {
		return nil
	}
	return g.ServerInfo
}

func (g *GetServerInfoResponse) GetError() *shared.Error {
	if g == nil {
		return nil
	}
	return g.Error
}
