// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListInvitationsRequest struct {
	// Status of organizations
	Status *string `queryParam:"style=form,explode=true,name=status"`
	// Status of organizations
	Organization *string `queryParam:"style=form,explode=true,name=organization"`
}

func (l *ListInvitationsRequest) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

func (l *ListInvitationsRequest) GetOrganization() *string {
	if l == nil {
		return nil
	}
	return l.Organization
}

type ListInvitationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of the invitations for the connected user
	ListInvitationsResponse *shared.ListInvitationsResponse
	// Error
	Error *shared.Error
}

func (l *ListInvitationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListInvitationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListInvitationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListInvitationsResponse) GetListInvitationsResponse() *shared.ListInvitationsResponse {
	if l == nil {
		return nil
	}
	return l.ListInvitationsResponse
}

func (l *ListInvitationsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
