// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"github.com/formancehq/formance-sdk-cloud-go/pkg/utils"
	"net/http"
)

type ListOrganizationApplicationsRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	PageSize       *int64 `default:"15" queryParam:"style=form,explode=true,name=pageSize"`
	Page           *int64 `default:"0" queryParam:"style=form,explode=true,name=page"`
}

func (l ListOrganizationApplicationsRequest) MarshalJSON() ([]byte, error) {
	return utils.MarshalJSON(l, "", false)
}

func (l *ListOrganizationApplicationsRequest) UnmarshalJSON(data []byte) error {
	if err := utils.UnmarshalJSON(data, &l, "", false, []string{"organizationId"}); err != nil {
		return err
	}
	return nil
}

func (l *ListOrganizationApplicationsRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListOrganizationApplicationsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListOrganizationApplicationsRequest) GetPage() *int64 {
	if l == nil {
		return nil
	}
	return l.Page
}

type ListOrganizationApplicationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of applications enabled for organization
	ListApplicationsResponse *shared.ListApplicationsResponse
	// Error
	Error *shared.Error
}

func (l *ListOrganizationApplicationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOrganizationApplicationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOrganizationApplicationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOrganizationApplicationsResponse) GetListApplicationsResponse() *shared.ListApplicationsResponse {
	if l == nil {
		return nil
	}
	return l.ListApplicationsResponse
}

func (l *ListOrganizationApplicationsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
