// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ListOrganizationsRequest struct {
	Expand *bool `queryParam:"style=form,explode=true,name=expand"`
}

func (l *ListOrganizationsRequest) GetExpand() *bool {
	if l == nil {
		return nil
	}
	return l.Expand
}

type ListOrganizationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of organizations
	ListOrganizationExpandedResponse *shared.ListOrganizationExpandedResponse
	// Error
	Error *shared.Error
}

func (l *ListOrganizationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOrganizationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOrganizationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOrganizationsResponse) GetListOrganizationExpandedResponse() *shared.ListOrganizationExpandedResponse {
	if l == nil {
		return nil
	}
	return l.ListOrganizationExpandedResponse
}

func (l *ListOrganizationsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
