// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListStacksRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Include deleted and disabled stacks
	All *bool `queryParam:"style=form,explode=true,name=all"`
	// Include deleted stacks
	//
	// Deprecated: This will be removed in a future release, please migrate away from it as soon as possible.
	Deleted *bool `queryParam:"style=form,explode=true,name=deleted"`
}

func (l *ListStacksRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListStacksRequest) GetAll() *bool {
	if l == nil {
		return nil
	}
	return l.All
}

func (l *ListStacksRequest) GetDeleted() *bool {
	if l == nil {
		return nil
	}
	return l.Deleted
}

type ListStacksResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of stacks
	ListStacksResponse *shared.ListStacksResponse
	// Error
	Error *shared.Error
}

func (l *ListStacksResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListStacksResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListStacksResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListStacksResponse) GetListStacksResponse() *shared.ListStacksResponse {
	if l == nil {
		return nil
	}
	return l.ListStacksResponse
}

func (l *ListStacksResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
