// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ListFeaturesRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (l *ListFeaturesRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

// ListFeaturesResponseBody - List of features
type ListFeaturesResponseBody struct {
	Data []shared.OrganizationFeature `json:"data"`
}

func (l *ListFeaturesResponseBody) GetData() []shared.OrganizationFeature {
	if l == nil {
		return []shared.OrganizationFeature{}
	}
	return l.Data
}

type ListFeaturesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of features
	Object *ListFeaturesResponseBody
	// Error
	Error *shared.Error
}

func (l *ListFeaturesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListFeaturesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListFeaturesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListFeaturesResponse) GetObject() *ListFeaturesResponseBody {
	if l == nil {
		return nil
	}
	return l.Object
}

func (l *ListFeaturesResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
