// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListLogsRequest struct {
	OrganizationID string         `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        *string        `queryParam:"style=form,explode=true,name=stackId"`
	Cursor         *string        `queryParam:"style=form,explode=true,name=cursor"`
	PageSize       *int64         `queryParam:"style=form,explode=true,name=pageSize"`
	Action         *shared.Action `queryParam:"style=form,explode=true,name=action"`
	UserID         *string        `queryParam:"style=form,explode=true,name=userId"`
	Key            *string        `queryParam:"style=form,explode=true,name=key"`
	Value          *string        `queryParam:"style=form,explode=true,name=value"`
}

func (l *ListLogsRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListLogsRequest) GetStackID() *string {
	if l == nil {
		return nil
	}
	return l.StackID
}

func (l *ListLogsRequest) GetCursor() *string {
	if l == nil {
		return nil
	}
	return l.Cursor
}

func (l *ListLogsRequest) GetPageSize() *int64 {
	if l == nil {
		return nil
	}
	return l.PageSize
}

func (l *ListLogsRequest) GetAction() *shared.Action {
	if l == nil {
		return nil
	}
	return l.Action
}

func (l *ListLogsRequest) GetUserID() *string {
	if l == nil {
		return nil
	}
	return l.UserID
}

func (l *ListLogsRequest) GetKey() *string {
	if l == nil {
		return nil
	}
	return l.Key
}

func (l *ListLogsRequest) GetValue() *string {
	if l == nil {
		return nil
	}
	return l.Value
}

type ListLogsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Cursor of logs
	LogCursor *shared.LogCursor
	// Error
	Error *shared.Error
}

func (l *ListLogsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListLogsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListLogsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListLogsResponse) GetLogCursor() *shared.LogCursor {
	if l == nil {
		return nil
	}
	return l.LogCursor
}

func (l *ListLogsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
