// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListApplicationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of applications
	ListApplicationsResponse *shared.ListApplicationsResponse
	// Error
	Error *shared.Error
}

func (l *ListApplicationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListApplicationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListApplicationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListApplicationsResponse) GetListApplicationsResponse() *shared.ListApplicationsResponse {
	if l == nil {
		return nil
	}
	return l.ListApplicationsResponse
}

func (l *ListApplicationsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
