// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListStackUsersAccessesRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
}

func (l *ListStackUsersAccessesRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListStackUsersAccessesRequest) GetStackID() string {
	if l == nil {
		return ""
	}
	return l.StackID
}

type ListStackUsersAccessesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Stack users access
	StackUserAccessResponse *shared.StackUserAccessResponse
	// Error
	Error *shared.Error
}

func (l *ListStackUsersAccessesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListStackUsersAccessesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListStackUsersAccessesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListStackUsersAccessesResponse) GetStackUserAccessResponse() *shared.StackUserAccessResponse {
	if l == nil {
		return nil
	}
	return l.StackUserAccessResponse
}

func (l *ListStackUsersAccessesResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
