// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ListUsersOfOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (l *ListUsersOfOrganizationRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

type ListUsersOfOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of users
	ListUsersResponse *shared.ListUsersResponse
	// Error
	Error *shared.Error
}

func (l *ListUsersOfOrganizationResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListUsersOfOrganizationResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListUsersOfOrganizationResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListUsersOfOrganizationResponse) GetListUsersResponse() *shared.ListUsersResponse {
	if l == nil {
		return nil
	}
	return l.ListUsersResponse
}

func (l *ListUsersOfOrganizationResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
