// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ListOrganizationsExpandedResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of organizations with expanded data
	ListOrganizationExpandedResponse *shared.ListOrganizationExpandedResponse
}

func (l *ListOrganizationsExpandedResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOrganizationsExpandedResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOrganizationsExpandedResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOrganizationsExpandedResponse) GetListOrganizationExpandedResponse() *shared.ListOrganizationExpandedResponse {
	if l == nil {
		return nil
	}
	return l.ListOrganizationExpandedResponse
}
