// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListOrganizationInvitationsRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	// Status of organizations
	Status *string `queryParam:"style=form,explode=true,name=status"`
}

func (l *ListOrganizationInvitationsRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListOrganizationInvitationsRequest) GetStatus() *string {
	if l == nil {
		return nil
	}
	return l.Status
}

type ListOrganizationInvitationsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of the invitations for the organization
	ListInvitationsResponse *shared.ListInvitationsResponse
	// Error
	Error *shared.Error
}

func (l *ListOrganizationInvitationsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListOrganizationInvitationsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListOrganizationInvitationsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListOrganizationInvitationsResponse) GetListInvitationsResponse() *shared.ListInvitationsResponse {
	if l == nil {
		return nil
	}
	return l.ListInvitationsResponse
}

func (l *ListOrganizationInvitationsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
