// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListModulesRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
}

func (l *ListModulesRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

func (l *ListModulesRequest) GetStackID() string {
	if l == nil {
		return ""
	}
	return l.StackID
}

type ListModulesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of modules
	ListModulesResponse *shared.ListModulesResponse
	// Error
	Error *shared.Error
}

func (l *ListModulesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListModulesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListModulesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListModulesResponse) GetListModulesResponse() *shared.ListModulesResponse {
	if l == nil {
		return nil
	}
	return l.ListModulesResponse
}

func (l *ListModulesResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
