// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ListPoliciesRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (l *ListPoliciesRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

type ListPoliciesResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of policies
	ListPoliciesResponse *shared.ListPoliciesResponse
	// Error
	Error *shared.Error
}

func (l *ListPoliciesResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListPoliciesResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListPoliciesResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListPoliciesResponse) GetListPoliciesResponse() *shared.ListPoliciesResponse {
	if l == nil {
		return nil
	}
	return l.ListPoliciesResponse
}

func (l *ListPoliciesResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
