// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ListRegionsRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (l *ListRegionsRequest) GetOrganizationID() string {
	if l == nil {
		return ""
	}
	return l.OrganizationID
}

type ListRegionsResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// List of the regions
	ListRegionsResponse *shared.ListRegionsResponse
	// Error
	Error *shared.Error
}

func (l *ListRegionsResponse) GetContentType() string {
	if l == nil {
		return ""
	}
	return l.ContentType
}

func (l *ListRegionsResponse) GetStatusCode() int {
	if l == nil {
		return 0
	}
	return l.StatusCode
}

func (l *ListRegionsResponse) GetRawResponse() *http.Response {
	if l == nil {
		return nil
	}
	return l.RawResponse
}

func (l *ListRegionsResponse) GetListRegionsResponse() *shared.ListRegionsResponse {
	if l == nil {
		return nil
	}
	return l.ListRegionsResponse
}

func (l *ListRegionsResponse) GetError() *shared.Error {
	if l == nil {
		return nil
	}
	return l.Error
}
