// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type OrganizationClientUpdateRequest struct {
	OrganizationID                  string                                  `pathParam:"style=simple,explode=false,name=organizationId"`
	ClientID                        string                                  `pathParam:"style=simple,explode=false,name=clientId"`
	UpdateOrganizationClientRequest *shared.UpdateOrganizationClientRequest `request:"mediaType=application/json"`
}

func (o *OrganizationClientUpdateRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientUpdateRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

func (o *OrganizationClientUpdateRequest) GetUpdateOrganizationClientRequest() *shared.UpdateOrganizationClientRequest {
	if o == nil {
		return nil
	}
	return o.UpdateOrganizationClientRequest
}

type OrganizationClientUpdateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (o *OrganizationClientUpdateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OrganizationClientUpdateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OrganizationClientUpdateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OrganizationClientUpdateResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
