// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type OrganizationClientDeleteRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ClientID       string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (o *OrganizationClientDeleteRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientDeleteRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

type OrganizationClientDeleteResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (o *OrganizationClientDeleteResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OrganizationClientDeleteResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OrganizationClientDeleteResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OrganizationClientDeleteResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
