// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type OrganizationClientsReadRequest struct {
	OrganizationID string  `pathParam:"style=simple,explode=false,name=organizationId"`
	Cursor         *string `queryParam:"style=form,explode=true,name=cursor"`
	PageSize       *int64  `queryParam:"style=form,explode=true,name=pageSize"`
}

func (o *OrganizationClientsReadRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientsReadRequest) GetCursor() *string {
	if o == nil {
		return nil
	}
	return o.Cursor
}

func (o *OrganizationClientsReadRequest) GetPageSize() *int64 {
	if o == nil {
		return nil
	}
	return o.PageSize
}

type OrganizationClientsReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Organization client
	ReadOrganizationClientsResponse *shared.ReadOrganizationClientsResponse
	// Error
	Error *shared.Error
}

func (o *OrganizationClientsReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OrganizationClientsReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OrganizationClientsReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OrganizationClientsReadResponse) GetReadOrganizationClientsResponse() *shared.ReadOrganizationClientsResponse {
	if o == nil {
		return nil
	}
	return o.ReadOrganizationClientsResponse
}

func (o *OrganizationClientsReadResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
