// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type OrganizationClientReadRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	ClientID       string `pathParam:"style=simple,explode=false,name=clientId"`
}

func (o *OrganizationClientReadRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientReadRequest) GetClientID() string {
	if o == nil {
		return ""
	}
	return o.ClientID
}

type OrganizationClientReadResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Organization client details
	ReadOrganizationClientResponse *shared.ReadOrganizationClientResponse
	// Error
	Error *shared.Error
}

func (o *OrganizationClientReadResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OrganizationClientReadResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OrganizationClientReadResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OrganizationClientReadResponse) GetReadOrganizationClientResponse() *shared.ReadOrganizationClientResponse {
	if o == nil {
		return nil
	}
	return o.ReadOrganizationClientResponse
}

func (o *OrganizationClientReadResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
