// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type OrganizationClientCreateRequest struct {
	OrganizationID                  string                                  `pathParam:"style=simple,explode=false,name=organizationId"`
	CreateOrganizationClientRequest *shared.CreateOrganizationClientRequest `request:"mediaType=application/json"`
}

func (o *OrganizationClientCreateRequest) GetOrganizationID() string {
	if o == nil {
		return ""
	}
	return o.OrganizationID
}

func (o *OrganizationClientCreateRequest) GetCreateOrganizationClientRequest() *shared.CreateOrganizationClientRequest {
	if o == nil {
		return nil
	}
	return o.CreateOrganizationClientRequest
}

type OrganizationClientCreateResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Organization client created
	CreateOrganizationClientResponse *shared.CreateOrganizationClientResponse
	// Error
	Error *shared.Error
}

func (o *OrganizationClientCreateResponse) GetContentType() string {
	if o == nil {
		return ""
	}
	return o.ContentType
}

func (o *OrganizationClientCreateResponse) GetStatusCode() int {
	if o == nil {
		return 0
	}
	return o.StatusCode
}

func (o *OrganizationClientCreateResponse) GetRawResponse() *http.Response {
	if o == nil {
		return nil
	}
	return o.RawResponse
}

func (o *OrganizationClientCreateResponse) GetCreateOrganizationClientResponse() *shared.CreateOrganizationClientResponse {
	if o == nil {
		return nil
	}
	return o.CreateOrganizationClientResponse
}

func (o *OrganizationClientCreateResponse) GetError() *shared.Error {
	if o == nil {
		return nil
	}
	return o.Error
}
