// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ReadAuthenticationProviderRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (r *ReadAuthenticationProviderRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

type ReadAuthenticationProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authentication provider details
	AuthenticationProviderResponse *shared.AuthenticationProviderResponse
	// Error
	Error *shared.Error
}

func (r *ReadAuthenticationProviderResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadAuthenticationProviderResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadAuthenticationProviderResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadAuthenticationProviderResponse) GetAuthenticationProviderResponse() *shared.AuthenticationProviderResponse {
	if r == nil {
		return nil
	}
	return r.AuthenticationProviderResponse
}

func (r *ReadAuthenticationProviderResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
