// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ReadStackUserAccessRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
	UserID         string `pathParam:"style=simple,explode=false,name=userId"`
}

func (r *ReadStackUserAccessRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *ReadStackUserAccessRequest) GetStackID() string {
	if r == nil {
		return ""
	}
	return r.StackID
}

func (r *ReadStackUserAccessRequest) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

type ReadStackUserAccessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Stack user access
	ReadStackUserAccess *shared.ReadStackUserAccess
	// Error
	Error *shared.Error
}

func (r *ReadStackUserAccessResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadStackUserAccessResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadStackUserAccessResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadStackUserAccessResponse) GetReadStackUserAccess() *shared.ReadStackUserAccess {
	if r == nil {
		return nil
	}
	return r.ReadStackUserAccess
}

func (r *ReadStackUserAccessResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
