// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ReadOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	Expand         *bool  `queryParam:"style=form,explode=true,name=expand"`
}

func (r *ReadOrganizationRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *ReadOrganizationRequest) GetExpand() *bool {
	if r == nil {
		return nil
	}
	return r.Expand
}

type ReadOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	ReadOrganizationResponse *shared.ReadOrganizationResponse
	// Error
	Error *shared.Error
}

func (r *ReadOrganizationResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadOrganizationResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadOrganizationResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadOrganizationResponse) GetReadOrganizationResponse() *shared.ReadOrganizationResponse {
	if r == nil {
		return nil
	}
	return r.ReadOrganizationResponse
}

func (r *ReadOrganizationResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
