// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ReadConnectedUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Read a user
	ReadUserResponse *shared.ReadUserResponse
	// Error
	Error *shared.Error
}

func (r *ReadConnectedUserResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadConnectedUserResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadConnectedUserResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadConnectedUserResponse) GetReadUserResponse() *shared.ReadUserResponse {
	if r == nil {
		return nil
	}
	return r.ReadUserResponse
}

func (r *ReadConnectedUserResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
