// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ReadUserOfOrganizationRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	UserID         string `pathParam:"style=simple,explode=false,name=userId"`
}

func (r *ReadUserOfOrganizationRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *ReadUserOfOrganizationRequest) GetUserID() string {
	if r == nil {
		return ""
	}
	return r.UserID
}

type ReadUserOfOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Read a user
	ReadOrganizationUserResponse *shared.ReadOrganizationUserResponse
	// Error
	Error *shared.Error
}

func (r *ReadUserOfOrganizationResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadUserOfOrganizationResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadUserOfOrganizationResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadUserOfOrganizationResponse) GetReadOrganizationUserResponse() *shared.ReadOrganizationUserResponse {
	if r == nil {
		return nil
	}
	return r.ReadOrganizationUserResponse
}

func (r *ReadUserOfOrganizationResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
