// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type ReadPolicyRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64  `pathParam:"style=simple,explode=false,name=policyId"`
}

func (r *ReadPolicyRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *ReadPolicyRequest) GetPolicyID() int64 {
	if r == nil {
		return 0
	}
	return r.PolicyID
}

type ReadPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Policy with scopes
	ReadPolicyResponse *shared.ReadPolicyResponse
	// Error
	Error *shared.Error
}

func (r *ReadPolicyResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadPolicyResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadPolicyResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadPolicyResponse) GetReadPolicyResponse() *shared.ReadPolicyResponse {
	if r == nil {
		return nil
	}
	return r.ReadPolicyResponse
}

func (r *ReadPolicyResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
