// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type ReadOrganizationClientRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
}

func (r *ReadOrganizationClientRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

type ReadOrganizationClientResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Organization client
	CreateClientResponseResponse *shared.CreateClientResponseResponse
	// Error
	Error *shared.Error
}

func (r *ReadOrganizationClientResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *ReadOrganizationClientResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *ReadOrganizationClientResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *ReadOrganizationClientResponse) GetCreateClientResponseResponse() *shared.CreateClientResponseResponse {
	if r == nil {
		return nil
	}
	return r.CreateClientResponseResponse
}

func (r *ReadOrganizationClientResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
