// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type RemoveScopeFromPolicyRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64  `pathParam:"style=simple,explode=false,name=policyId"`
	ScopeID        int64  `pathParam:"style=simple,explode=false,name=scopeId"`
}

func (r *RemoveScopeFromPolicyRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *RemoveScopeFromPolicyRequest) GetPolicyID() int64 {
	if r == nil {
		return 0
	}
	return r.PolicyID
}

func (r *RemoveScopeFromPolicyRequest) GetScopeID() int64 {
	if r == nil {
		return 0
	}
	return r.ScopeID
}

type RemoveScopeFromPolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (r *RemoveScopeFromPolicyResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RemoveScopeFromPolicyResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RemoveScopeFromPolicyResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RemoveScopeFromPolicyResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
