// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type RestoreStackRequest struct {
	OrganizationID string `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string `pathParam:"style=simple,explode=false,name=stackId"`
}

func (r *RestoreStackRequest) GetOrganizationID() string {
	if r == nil {
		return ""
	}
	return r.OrganizationID
}

func (r *RestoreStackRequest) GetStackID() string {
	if r == nil {
		return ""
	}
	return r.StackID
}

type RestoreStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// OK
	CreateStackResponse *shared.CreateStackResponse
	// Error
	Error *shared.Error
}

func (r *RestoreStackResponse) GetContentType() string {
	if r == nil {
		return ""
	}
	return r.ContentType
}

func (r *RestoreStackResponse) GetStatusCode() int {
	if r == nil {
		return 0
	}
	return r.StatusCode
}

func (r *RestoreStackResponse) GetRawResponse() *http.Response {
	if r == nil {
		return nil
	}
	return r.RawResponse
}

func (r *RestoreStackResponse) GetCreateStackResponse() *shared.CreateStackResponse {
	if r == nil {
		return nil
	}
	return r.CreateStackResponse
}

func (r *RestoreStackResponse) GetError() *shared.Error {
	if r == nil {
		return nil
	}
	return r.Error
}
