// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type UpdateApplicationRequest struct {
	ApplicationID   string                  `pathParam:"style=simple,explode=false,name=applicationId"`
	ApplicationData *shared.ApplicationData `request:"mediaType=application/json"`
}

func (u *UpdateApplicationRequest) GetApplicationID() string {
	if u == nil {
		return ""
	}
	return u.ApplicationID
}

func (u *UpdateApplicationRequest) GetApplicationData() *shared.ApplicationData {
	if u == nil {
		return nil
	}
	return u.ApplicationData
}

type UpdateApplicationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Application updated
	UpdateApplicationResponse *shared.UpdateApplicationResponse
	// Error
	Error *shared.Error
}

func (u *UpdateApplicationResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateApplicationResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateApplicationResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateApplicationResponse) GetUpdateApplicationResponse() *shared.UpdateApplicationResponse {
	if u == nil {
		return nil
	}
	return u.UpdateApplicationResponse
}

func (u *UpdateApplicationResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
