// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type UpdatePolicyRequest struct {
	OrganizationID string             `pathParam:"style=simple,explode=false,name=organizationId"`
	PolicyID       int64              `pathParam:"style=simple,explode=false,name=policyId"`
	PolicyData     *shared.PolicyData `request:"mediaType=application/json"`
}

func (u *UpdatePolicyRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpdatePolicyRequest) GetPolicyID() int64 {
	if u == nil {
		return 0
	}
	return u.PolicyID
}

func (u *UpdatePolicyRequest) GetPolicyData() *shared.PolicyData {
	if u == nil {
		return nil
	}
	return u.PolicyData
}

type UpdatePolicyResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Policy updated
	UpdatePolicyResponse *shared.UpdatePolicyResponse
	// Error
	Error *shared.Error
}

func (u *UpdatePolicyResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdatePolicyResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdatePolicyResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdatePolicyResponse) GetUpdatePolicyResponse() *shared.UpdatePolicyResponse {
	if u == nil {
		return nil
	}
	return u.UpdatePolicyResponse
}

func (u *UpdatePolicyResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
