// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type UpdateStackRequest struct {
	OrganizationID string            `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string            `pathParam:"style=simple,explode=false,name=stackId"`
	StackData      *shared.StackData `request:"mediaType=application/json"`
}

func (u *UpdateStackRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpdateStackRequest) GetStackID() string {
	if u == nil {
		return ""
	}
	return u.StackID
}

func (u *UpdateStackRequest) GetStackData() *shared.StackData {
	if u == nil {
		return nil
	}
	return u.StackData
}

type UpdateStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Updated stack
	CreateStackResponse *shared.CreateStackResponse
	// Error
	Error *shared.Error
}

func (u *UpdateStackResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateStackResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateStackResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateStackResponse) GetCreateStackResponse() *shared.CreateStackResponse {
	if u == nil {
		return nil
	}
	return u.CreateStackResponse
}

func (u *UpdateStackResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
