// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type UpdateOrganizationRequest struct {
	OrganizationID   string                   `pathParam:"style=simple,explode=false,name=organizationId"`
	OrganizationData *shared.OrganizationData `request:"mediaType=application/json"`
}

func (u *UpdateOrganizationRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpdateOrganizationRequest) GetOrganizationData() *shared.OrganizationData {
	if u == nil {
		return nil
	}
	return u.OrganizationData
}

type UpdateOrganizationResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Organization updated
	ReadOrganizationResponse *shared.ReadOrganizationResponse
	// Error
	Error *shared.Error
}

func (u *UpdateOrganizationResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpdateOrganizationResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpdateOrganizationResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpdateOrganizationResponse) GetReadOrganizationResponse() *shared.ReadOrganizationResponse {
	if u == nil {
		return nil
	}
	return u.ReadOrganizationResponse
}

func (u *UpdateOrganizationResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
