// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type UpgradeStackRequest struct {
	OrganizationID string               `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID        string               `pathParam:"style=simple,explode=false,name=stackId"`
	StackVersion   *shared.StackVersion `request:"mediaType=application/json"`
}

func (u *UpgradeStackRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpgradeStackRequest) GetStackID() string {
	if u == nil {
		return ""
	}
	return u.StackID
}

func (u *UpgradeStackRequest) GetStackVersion() *shared.StackVersion {
	if u == nil {
		return nil
	}
	return u.StackVersion
}

type UpgradeStackResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (u *UpgradeStackResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpgradeStackResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpgradeStackResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpgradeStackResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
