// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/formance-sdk-cloud-go/pkg/models/shared"
	"net/http"
)

type UpsertAuthenticationProviderRequest struct {
	OrganizationID             string                             `pathParam:"style=simple,explode=false,name=organizationId"`
	AuthenticationProviderData *shared.AuthenticationProviderData `request:"mediaType=application/json"`
}

func (u *UpsertAuthenticationProviderRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpsertAuthenticationProviderRequest) GetAuthenticationProviderData() *shared.AuthenticationProviderData {
	if u == nil {
		return nil
	}
	return u.AuthenticationProviderData
}

type UpsertAuthenticationProviderResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Authentication provider created or updated
	AuthenticationProviderResponse *shared.AuthenticationProviderResponse
	// Error
	Error *shared.Error
}

func (u *UpsertAuthenticationProviderResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertAuthenticationProviderResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertAuthenticationProviderResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertAuthenticationProviderResponse) GetAuthenticationProviderResponse() *shared.AuthenticationProviderResponse {
	if u == nil {
		return nil
	}
	return u.AuthenticationProviderResponse
}

func (u *UpsertAuthenticationProviderResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
