// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type UpsertOrganizationUserRequest struct {
	OrganizationID                string                                `pathParam:"style=simple,explode=false,name=organizationId"`
	UserID                        string                                `pathParam:"style=simple,explode=false,name=userId"`
	UpdateOrganizationUserRequest *shared.UpdateOrganizationUserRequest `request:"mediaType=application/json"`
}

func (u *UpsertOrganizationUserRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpsertOrganizationUserRequest) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpsertOrganizationUserRequest) GetUpdateOrganizationUserRequest() *shared.UpdateOrganizationUserRequest {
	if u == nil {
		return nil
	}
	return u.UpdateOrganizationUserRequest
}

type UpsertOrganizationUserResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (u *UpsertOrganizationUserResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertOrganizationUserResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertOrganizationUserResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertOrganizationUserResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
