// Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.

package operations

import (
	"github.com/formancehq/terraform-provider-cloud/pkg/membership_client/pkg/models/shared"
	"net/http"
)

type UpsertStackUserAccessRequest struct {
	OrganizationID         string                         `pathParam:"style=simple,explode=false,name=organizationId"`
	StackID                string                         `pathParam:"style=simple,explode=false,name=stackId"`
	UserID                 string                         `pathParam:"style=simple,explode=false,name=userId"`
	UpdateStackUserRequest *shared.UpdateStackUserRequest `request:"mediaType=application/json"`
}

func (u *UpsertStackUserAccessRequest) GetOrganizationID() string {
	if u == nil {
		return ""
	}
	return u.OrganizationID
}

func (u *UpsertStackUserAccessRequest) GetStackID() string {
	if u == nil {
		return ""
	}
	return u.StackID
}

func (u *UpsertStackUserAccessRequest) GetUserID() string {
	if u == nil {
		return ""
	}
	return u.UserID
}

func (u *UpsertStackUserAccessRequest) GetUpdateStackUserRequest() *shared.UpdateStackUserRequest {
	if u == nil {
		return nil
	}
	return u.UpdateStackUserRequest
}

type UpsertStackUserAccessResponse struct {
	// HTTP response content type for this operation
	ContentType string
	// HTTP response status code for this operation
	StatusCode int
	// Raw HTTP response; suitable for custom response parsing
	RawResponse *http.Response
	// Error
	Error *shared.Error
}

func (u *UpsertStackUserAccessResponse) GetContentType() string {
	if u == nil {
		return ""
	}
	return u.ContentType
}

func (u *UpsertStackUserAccessResponse) GetStatusCode() int {
	if u == nil {
		return 0
	}
	return u.StatusCode
}

func (u *UpsertStackUserAccessResponse) GetRawResponse() *http.Response {
	if u == nil {
		return nil
	}
	return u.RawResponse
}

func (u *UpsertStackUserAccessResponse) GetError() *shared.Error {
	if u == nil {
		return nil
	}
	return u.Error
}
