// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-cloud/pkg (interfaces: TokenProviderImpl)
//
// Generated by this command:
//
//	mockgen -destination=tokenprovider_generated.go -package=pkg . TokenProviderImpl
//

// Package pkg is a generated GoMock package.
package pkg

import (
	context "context"
	reflect "reflect"

	oidc "github.com/zitadel/oidc/v3/pkg/oidc"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenProviderImpl is a mock of TokenProviderImpl interface.
type MockTokenProviderImpl struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderImplMockRecorder
	isgomock struct{}
}

// MockTokenProviderImplMockRecorder is the mock recorder for MockTokenProviderImpl.
type MockTokenProviderImplMockRecorder struct {
	mock *MockTokenProviderImpl
}

// NewMockTokenProviderImpl creates a new mock instance.
func NewMockTokenProviderImpl(ctrl *gomock.Controller) *MockTokenProviderImpl {
	mock := &MockTokenProviderImpl{ctrl: ctrl}
	mock.recorder = &MockTokenProviderImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProviderImpl) EXPECT() *MockTokenProviderImplMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockTokenProviderImpl) AccessToken(ctx context.Context) (*TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", ctx)
	ret0, _ := ret[0].(*TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockTokenProviderImplMockRecorder) AccessToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).AccessToken), ctx)
}

// IntrospectToken mocks base method.
func (m *MockTokenProviderImpl) IntrospectToken(ctx context.Context) (oidc.IntrospectionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IntrospectToken", ctx)
	ret0, _ := ret[0].(oidc.IntrospectionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IntrospectToken indicates an expected call of IntrospectToken.
func (mr *MockTokenProviderImplMockRecorder) IntrospectToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IntrospectToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).IntrospectToken), ctx)
}

// RefreshToken mocks base method.
func (m *MockTokenProviderImpl) RefreshToken(ctx context.Context) (*TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx)
	ret0, _ := ret[0].(*TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockTokenProviderImplMockRecorder) RefreshToken(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).RefreshToken), ctx)
}
