// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/formancehq/terraform-provider-cloud/pkg (interfaces: TokenProviderImpl)
//
// Generated by this command:
//
//	mockgen -typed -destination=tokenprovider_generated.go -package=pkg . TokenProviderImpl
//

// Package pkg is a generated GoMock package.
package pkg

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTokenProviderImpl is a mock of TokenProviderImpl interface.
type MockTokenProviderImpl struct {
	ctrl     *gomock.Controller
	recorder *MockTokenProviderImplMockRecorder
	isgomock struct{}
}

// MockTokenProviderImplMockRecorder is the mock recorder for MockTokenProviderImpl.
type MockTokenProviderImplMockRecorder struct {
	mock *MockTokenProviderImpl
}

// NewMockTokenProviderImpl creates a new mock instance.
func NewMockTokenProviderImpl(ctrl *gomock.Controller) *MockTokenProviderImpl {
	mock := &MockTokenProviderImpl{ctrl: ctrl}
	mock.recorder = &MockTokenProviderImplMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenProviderImpl) EXPECT() *MockTokenProviderImplMockRecorder {
	return m.recorder
}

// AccessToken mocks base method.
func (m *MockTokenProviderImpl) AccessToken(ctx context.Context) (*TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessToken", ctx)
	ret0, _ := ret[0].(*TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AccessToken indicates an expected call of AccessToken.
func (mr *MockTokenProviderImplMockRecorder) AccessToken(ctx any) *MockTokenProviderImplAccessTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).AccessToken), ctx)
	return &MockTokenProviderImplAccessTokenCall{Call: call}
}

// MockTokenProviderImplAccessTokenCall wrap *gomock.Call
type MockTokenProviderImplAccessTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenProviderImplAccessTokenCall) Return(arg0 *TokenInfo, arg1 error) *MockTokenProviderImplAccessTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenProviderImplAccessTokenCall) Do(f func(context.Context) (*TokenInfo, error)) *MockTokenProviderImplAccessTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenProviderImplAccessTokenCall) DoAndReturn(f func(context.Context) (*TokenInfo, error)) *MockTokenProviderImplAccessTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// OrganizationId mocks base method.
func (m *MockTokenProviderImpl) OrganizationId(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OrganizationId", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OrganizationId indicates an expected call of OrganizationId.
func (mr *MockTokenProviderImplMockRecorder) OrganizationId(ctx any) *MockTokenProviderImplOrganizationIdCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrganizationId", reflect.TypeOf((*MockTokenProviderImpl)(nil).OrganizationId), ctx)
	return &MockTokenProviderImplOrganizationIdCall{Call: call}
}

// MockTokenProviderImplOrganizationIdCall wrap *gomock.Call
type MockTokenProviderImplOrganizationIdCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenProviderImplOrganizationIdCall) Return(arg0 string, arg1 error) *MockTokenProviderImplOrganizationIdCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenProviderImplOrganizationIdCall) Do(f func(context.Context) (string, error)) *MockTokenProviderImplOrganizationIdCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenProviderImplOrganizationIdCall) DoAndReturn(f func(context.Context) (string, error)) *MockTokenProviderImplOrganizationIdCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RefreshToken mocks base method.
func (m *MockTokenProviderImpl) RefreshToken(ctx context.Context) (*TokenInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshToken", ctx)
	ret0, _ := ret[0].(*TokenInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RefreshToken indicates an expected call of RefreshToken.
func (mr *MockTokenProviderImplMockRecorder) RefreshToken(ctx any) *MockTokenProviderImplRefreshTokenCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshToken", reflect.TypeOf((*MockTokenProviderImpl)(nil).RefreshToken), ctx)
	return &MockTokenProviderImplRefreshTokenCall{Call: call}
}

// MockTokenProviderImplRefreshTokenCall wrap *gomock.Call
type MockTokenProviderImplRefreshTokenCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTokenProviderImplRefreshTokenCall) Return(arg0 *TokenInfo, arg1 error) *MockTokenProviderImplRefreshTokenCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTokenProviderImplRefreshTokenCall) Do(f func(context.Context) (*TokenInfo, error)) *MockTokenProviderImplRefreshTokenCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTokenProviderImplRefreshTokenCall) DoAndReturn(f func(context.Context) (*TokenInfo, error)) *MockTokenProviderImplRefreshTokenCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
